/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uah.cs321;

import java.util.Date;
import javax.swing.JLabel;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author David
 */
public class EmailListItem extends javax.swing.JPanel {

	/**
	 * Creates new form EmailListItem
	 */
	public EmailListItem(Email email) {
		this.email = email;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		jLabel4 = new JLabel();

		jLabel1.setText("jLabel1");

		setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
		setPreferredSize(new Dimension(967, 64));
		addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent evt) {
				formMouseClicked(evt);
			}
		});

		jLabel2.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
		jLabel2.setText(this.email.getRecipient());

		jLabel3.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
		jLabel3.setText(this.email.getTimeStamp().toString());

		jLabel4.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
		jLabel4.setText(this.email.getSender());

		javax.swing.GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2)
								.addGap(392, 392, 392)
								.addComponent(jLabel4)
								.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
								.addComponent(jLabel3)
								.addContainerGap())
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel2)
										.addComponent(jLabel3)
										.addComponent(jLabel4))
								.addContainerGap(19, Short.MAX_VALUE))
		);
	}

	private void formMouseClicked(MouseEvent evt) {
		new EmailView(null, true).setVisible(true);
	}

	private Email email;
	private JLabel jLabel1;
	private JLabel jLabel2;
	private JLabel jLabel3;
	private JLabel jLabel4;
}
